### github-action-variable-01.yml

name : Test Github Actions variable-01
on:
  push

env:
  DAY_OF_WEEK: Friday

job:
  check-var:
    runs-on: ubuntu-latest
    steps:
      - name: "It's Friday"
        run: echo "Today is $DAY_OF_WEEK!"
